In [1]:
import numpy as np
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Perform a vectorized operation
result = arr * 2

In [2]:
print(result)

[[ 2  4  6]
 [ 8 10 12]]


In [3]:
arr = np.array([1, 2, 3])
print(arr)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr = np.array((1, 3, 2))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


In [30]:
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])
arr2 = arr[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)#review this later
arr3 = arr[[1, 1, 0, 3], [3, 2, 1, 0]] #review this later
print ("\nElements at indices (1, 3), (1, 2), (0, 1), (3, 0):\n", arr3)

first 2 rows and alternate columns(0 and 2):
 [[-1.   4. ]
 [ 4.   0. ]
 [ 2.6  8. ]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [5]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])
print ("Adding 1 to every element:", a + 1)
print ("\nSubtracting 2 from each element:", b - 2)
print ("\nSum of all array elements: ", a.sum())
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [45]:
x = np.array([1, 2])
print(x.dtype)
x = np.array([1.0, 2.0])
print(x.dtype)
x = np.array([1, 2], dtype = np.int32)
print(x.dtype)

int64
float64
int32


In [8]:
array = [9, 2, 7, 200, 5]

arr = np.array(array)

print(array)


[9, 2, 7, 200, 5]


In [14]:
array = [9, 2, 7, 200, 5,9]
#create a 2 X 3 dimension array 
arr = np.array(array).reshape(2,3)

print(arr)

[[  9   2   7]
 [200   5   9]]


In [16]:
#change dimension 
arr2= np.array(array).reshape(3,2)
print(arr2)

[[  9   2]
 [  7 200]
 [  5   9]]


In [17]:
arr1 = np.array([[4, 7], [2, 6]], dtype = np.float64)
arr2 = np.array([[3, 6], [2, 8]], dtype = np.float64)

In [48]:
arr5= np.array([[4, 7]], dtype = np.float64)

In [50]:
T5= arr5.T
T5

array([[4.],
       [7.]])

In [18]:
Sum = np.add(arr1, arr2)
print(Sum)

[[ 7. 13.]
 [ 4. 14.]]


In [19]:
Sum1 = np.sum(arr1)
print(Sum1)

19.0


In [20]:
Sqrt = np.sqrt(arr1)
print(Sqrt)

[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [47]:
print(arr1)

[[4. 7.]
 [2. 6.]]


In [21]:
Trans_arr = arr1.T

In [22]:
print(Trans_arr)

[[4. 2.]
 [7. 6.]]


In [32]:
lrgarr=list(range(0,15,3))# when woud this be useful?
print(lrgarr)

[0, 3, 6, 9, 12]


In [33]:
lrgarr=list(range(100))
print(lrgarr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [42]:
arr3 = np.array(lrgarr).reshape(2,50) # so shape must be even? what are other rules I should know?

In [43]:
print(arr3)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
  98 99]]


In [44]:
arr3.shape

(2, 50)

In [39]:
arr3 = np.array(lrgarr).reshape(10,10)

In [40]:
print(arr3)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [29]:
arr3.shape

(10, 10)

In [52]:
x=list(range(54))

In [53]:
arr6 = np.array(x).reshape(6,9)

In [54]:
print(arr6)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]]


In [57]:
new_arr = arr6[2:, ::3]
print(new_arr)

[[18 21 24]
 [27 30 33]
 [36 39 42]
 [45 48 51]]


In [62]:
print(new_arr.shape)

(4, 3)


In [58]:
oned = new_arr.flatten()

In [59]:
oned

array([18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51])

In [60]:
oned_2 = new_arr.reshape(1,-1)

In [61]:
oned_2

array([[18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51]])

In [72]:
oned_3= new_arr.copy()

In [74]:
y=oned_3.resize((12,))

In [76]:
print(y)

None
